### PR TITLE
ProxyAuthenticator enhancements

### PR DESCRIPTION
**Pull request by k-sever**
Changed ProxyAuthenticator to be more generic. It accepts AuthorizationHeader and HttpRequest

Repack of https://github.com/verygoodsecurity/LittleProxy/pull/3 and https://github.com/verygoodsecurity/LittleProxy/pull/4

### CODE REVIEW

**Comment by mjallday** [comment]
Looks good. Did we have to bump the build version number?

**Comment by k-sever** [comment]
> Did we have to bump the build version number?

What do you mean? We are using `1.1.3-SNAPSHOT-VGS` version since it's a fork of `1.1.3-SNAPSHOT` of `adamfisk/master` + our fixes.
And I believe we need to do rebase when syncing with `adamfisk/master`. Then we will have a clean git history with all our fixes on top of `adamfisk/master`. (see #7)

**Comment by k-sever** [comment]
I'll create the same PR for adamfisk/LittleProxy to substitute https://github.com/adamfisk/LittleProxy/pull/356 and https://github.com/adamfisk/LittleProxy/pull/351. I don't see any activity/comments of those PRs however (

**Comment by k-sever** [comment]
Let's not merge this one for now : https://github.com/verygoodsecurity/vault/issues/1006#issuecomment-293687869

**Comment by mjallday** [comment]
@k-sever can we merge this?

**Review by mjallday — APPROVED** [review]
👍

**Comment by zdmytriv** [comment]
[ch2260]

**Pull request merged**
